# 1. 安装tpm: mkdir -p ~/.tmux/plugins && cd ~/.tmux/plugins && git clone https://github.com/tmux-plugins/tpm
# 2. 按 prefix + I(大写) 来安装插件
# 3. 安装 vim-obsession, 用 vundle 安装或: cd ~/.vim/bundle && git clone git://github.com/tpope/vim-obsession.git --depth 1 && vim -u NONE -c "helptags vim-obsession/doc" -c q
##### 以上需手工执行 #####

## 修改 tmux-prefix 键: ctrl+b --> ctrl+a
set -g prefix C-x
unbind C-b
bind C-x send-prefix
#set-option -g prefix2 `

## 鼠标支持
set -g mouse on

## 基础配置
set -g default-terminal "screen-256color"  # 开启 256 colors 支持
set -g display-time 3000
set -g history-limit 65535




## 面板相关
# 分隔面板
unbind '"'
bind - splitw -v -c '#{pane_current_path}'
unbind %
bind | splitw -h -c '#{pane_current_path}'

# 面板(pane)切换
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R
bind -r e lastp # 选择最后一个面板
bind -r ^e last # 选择最后一个窗口
bind -r ^u swapp -U # 与前一个面板交换位置
bind -r ^d swapp -D # 与后一个面板交换位置
# -r表示可重复按键，大概500ms之内，重复的h、j、k、l按键都将有效，完美支持了快速切换的Geek需求

# 调整面板大小：绑定 Ctrl + h/j/k/l 键调整pane边缘
bind -r ^k resizep -U 10 # upward (prefix Ctrl+k)
bind -r ^j resizep -D 10 # downward (prefix Ctrl+j)
bind -r ^h resizep -L 10 # to the left (prefix Ctrl+h)
bind -r ^l resizep -R 10 # to the right (prefix Ctrl+l)


setw -g mode-keys vi # 设置为vi编辑模式

## 其他杂项配置
bind r source-file ~/.tmux.conf \; display-message "source-file ~/.tmux.conf done"  # 绑定重载 settings 的热键
bind m command-prompt "splitw -h 'exec man %%'"  # 绑定m键为在新的panel打开man


## 一些锦上添花的优化
# 设置窗口面板起始序号
set -g base-index 1  # 设置窗口(window)的起始下标为1
set -g pane-base-index 1  # 设置面板(pane)的起始下标为1

# 关闭默认的rename机制
setw -g automatic-rename off  # tmux默认会自动重命名窗口，频繁的命令行操作，将频繁触发重命名，比较浪费CPU性能
setw -g allow-rename off


# 自定义状态栏
set -g status-interval 1 # 状态栏刷新时间
set -g status-justify left # 状态栏列表左对齐
setw -g monitor-activity on # 非当前窗口有内容更新时在状态栏通知

set -g status-left "#[bg=#88cc44] Sess: #S " # 状态栏-左侧内容 (#S: 会话(session)名称)
set -g status-left-length 300 # 状态栏-左边长度300
set -g status-right-length 500 # 状态栏-左边长度500

set -wg window-status-format " #I:#W " # 状态栏-(当前窗口除外的其他)窗口名称格式
set -wg window-status-separator "" # 状态栏-窗口名称之间的间隔
set -wg window-status-current-format " #I:#W #F " # 状态栏-当前窗口名称格式(#I：序号，#w：窗口名称，#F：间隔符)
set -wg window-status-current-style "bg=black, fg=yellow" # 状态栏-当前窗口名称的背景色

set -g message-style "bg=#202529, fg=#91A8BA" # 指定消息通知的前景、后景色
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -i"

# plugin 

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
run '~/.tmux/plugins/tpm/tpm'
